server:
  port: 8085

management:
  endpoints:
    web:
      exposure:
        include: '*'
  security:
    enabled: false

spring:
  application:
    name: gateway-service
  cloud:
    nacos:
      config:
        server-addr: http://localhost:8848
      discovery:
        server-addr:  http://localhost:8848
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: item-service
          uri: lb://item-service
          predicates:
            - Path=/item/**
          filters:
            - StripPrefix=1
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/order/**
          filters:
            - StripPrefix=1
    sentinel:
      transport:
        dashboard: localhost:8858
        port: 8719
      eager: true
      datasource:
        na:
          nacos:
            server-addr: http://localhost:8848
            groupId: DEFAULT_GROUP
            dataId: gateway-sentinel
            rule-type: flow
  redis:
    host: localhost
    port: 6379
    lettuce:
      pool:
        max-active: 8
        max-wait: 1ms
        max-idle: 8
        min-idle: 0