server:
  port: 8086

spring:
  application:
    name: order-service
  nacos:
    discovery:
      server-addr: http://localhost:8848

rocketmq:
  name-server: http://127.0.0.1:9876
  producer:
    group: user-group
    send-message-timeout: 3000