server:
  port: 8087


spring:
  application:
    name: item-service
  nacos:
    discovery:
      server-addr: http://localhost:8848
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest



